export const SUPABASE_STORAGE_BUCKET = 'resumes'

export const USER_TYPES = {
  CANDIDATE: 'candidate' as const,
  RECRUITER: 'recruiter' as const,
}

export const FREE_UNLOCKS_LIMIT = 10
export const CREDITS_PER_UNLOCK = 1

export const SKILL_SUGGESTIONS = [
  'JavaScript',
  'TypeScript',
  'React',
  'Vue.js',
  'Angular',
  'Node.js',
  'Python',
  'Java',
  'C#',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'HTML',
  'CSS',
  'SASS',
  'Tailwind CSS',
  'Bootstrap',
  'jQuery',
  'Express.js',
  'Next.js',
  'Nuxt.js',
  'Django',
  'Flask',
  'Spring Boot',
  'Laravel',
  'Ruby on Rails',
  'ASP.NET',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'Redis',
  'Elasticsearch',
  'AWS',
  'Azure',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'Git',
  'GraphQL',
  'REST API',
  'Microservices',
  'DevOps',
  'CI/CD',
  'Testing',
  'Jest',
  'Cypress',
  'Selenium',
  'Machine Learning',
  'AI',
  'Data Science',
  'Analytics',
  'Blockchain',
  'Mobile Development',
  'iOS',
  'Android',
  'React Native',
  'Flutter',
  'Unity',
  'Game Development',
  'UI/UX Design',
  'Figma',
  'Adobe Creative Suite',
  'Project Management',
  'Agile',
  'Scrum',
  'Leadership',
  'Team Management'
]

export const EXPERIENCE_RANGES = [
  { label: 'Entry Level (0-2 years)', min: 0, max: 2 },
  { label: 'Mid Level (3-5 years)', min: 3, max: 5 },
  { label: 'Senior Level (6-10 years)', min: 6, max: 10 },
  { label: 'Expert Level (10+ years)', min: 10, max: 50 },
]

export const LOCATIONS = [
  'Remote',
  'San Francisco, CA',
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'Austin, TX',
  'Seattle, WA',
  'Boston, MA',
  'Denver, CO',
  'Atlanta, GA',
  'Miami, FL',
  'Dallas, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'Houston, TX',
  'Washington, DC',
  'Portland, OR',
  'Nashville, TN',
  'Raleigh, NC',
  'Salt Lake City, UT',
]